#!/bin/sh

# Check if Docker Compose is running any containers
cd /home/ec2-user
containers_running=$(docker-compose ps -q)

if [ -n "$containers_running" ]; then
    echo "Stopping Docker containers..."
    docker-compose down
    echo "Docker containers stopped."
else
    echo "No Docker containers are running."
fi
