on:
  push:
  
jobs:
  test:
    name: Test on node 20.x and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js '20.x'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: npm install, build and test
      run: |
        cd frontend
        npm install
        npm run build --if-present
        npm test
